# Generated by Django 5.2.6 on 2025-09-28 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="""
                    CREATE EXTENSION IF NOT EXISTS btree_gist;
                    CREATE EXTENSION IF NOT EXISTS pg_trgm;
                """,
            reverse_sql="""
                    DROP EXTENSION IF EXISTS btree_gist;
                    DROP EXTENSION IF EXISTS pg_trgm;
                """
        ),
    ]
