# Generated by Django 5.2.6 on 2025-09-24 05:09

import django.contrib.postgres.constraints
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Entity Type',
                'verbose_name_plural': 'Entity Types',
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['uuid'], name='entities_en_uuid_521bb5_btree')],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=255)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='entities.entitytype')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['uuid'], name='entities_en_uuid_177390_btree'), models.Index(fields=['display_name'], name='entities_en_display_c82a12_idx')],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.F('uuid'), '='), (models.Func(models.F('valid_from'), models.F('valid_to'), function='tstzrange'), '&&')], name='no_overlap_entity_versions'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('uuid',), name='unique_current_uuid')],
            },
        ),
    ]
