# Generated by Django 5.2.6 on 2025-09-25 07:30

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entity',
            name='entities_en_uuid_177390_btree',
        ),
        migrations.RemoveIndex(
            model_name='entitydetail',
            name='entities_en_uuid_396851_btree',
        ),
        migrations.RemoveIndex(
            model_name='entitytype',
            name='entities_en_uuid_521bb5_btree',
        ),
        migrations.AddField(
            model_name='entity',
            name='hash_diff',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='entitydetail',
            name='hash_diff',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=django.contrib.postgres.indexes.GistIndex(fields=['uuid'], name='idx_uuid_gist_entity'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=django.contrib.postgres.indexes.GistIndex(fields=['hash_diff'], name='idx_hd_gist_entity'),
        ),
        migrations.AddIndex(
            model_name='entitydetail',
            index=django.contrib.postgres.indexes.GistIndex(fields=['uuid'], name='idx_uuid_gist_entity_detail'),
        ),
        migrations.AddIndex(
            model_name='entitydetail',
            index=django.contrib.postgres.indexes.GistIndex(fields=['hash_diff'], name='idx_hd_gist_entity_detail'),
        ),
        migrations.AddIndex(
            model_name='entitytype',
            index=django.contrib.postgres.indexes.GistIndex(fields=['uuid'], name='idx_uuid_gist_entity_type'),
        ),
    ]
