# Generated by Django 5.2.6 on 2025-09-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_remove_entity_entities_en_uuid_177390_btree_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entitydetail',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('entity_uuid',), name='unique_current_per_entity_uuid'),
        ),
    ]
