# Generated by Django 5.2.6 on 2025-09-27 14:57

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_entitydetail_unique_current_per_entity_uuid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entitydetail',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.F('entity_uuid'), '='), (models.F('detail_code'), '='), (models.Func(models.F('valid_from'), models.Func(models.F('valid_to'), models.Value('infinity'), function='COALESCE'), function='TSTZRANGE'), '&&')], name='exclude_overlapping_entity_detail'),
        ),
    ]
